version: '2'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "routes:app"
    ports:
     - "8000:8000"
    volumes:
     - .:/code
  #   depends_on:
  #    - postgres
  # postgres:
  #   image: postgres
